default_stages: [ commit, merge-commit, push, prepare-commit-msg, commit-msg,
                  post-checkout, post-commit, post-merge, post-rewrite ]
exclude: |
  (?x)(
  LICENSE|
  \.(html|csv|svg)$|
  EAB_tools/tools.py  # This is old code
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed.
      - id: check-ast  # Simply check whether files parse as valid python.
      - id: check-case-conflict  # Check for files with names that would conflict on a
                                 # case-insensitive filesystem like macOS HFS+ or
                                 # Windows FAT.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml  # checks toml files for parseable syntax.
      - id: check-yaml  # checks yaml files for parseable syntax.
      - id: destroyed-symlinks  # Detects symlinks which are changed to regular files
                                # with a content of a path which that symlink was
                                # pointing to. This usually happens on Windows when a
                                # user clones a repository that has symlinks, but they
                                # do not have the permission to create symlinks.
      - id: detect-private-key  # Checks for the existence of private keys.
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
      - id: mixed-line-ending  # Replaces or checks mixed line ending.
      - id: trailing-whitespace  # Trims trailing whitespace.

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.6.22
          - flake8-comprehensions==3.10.0
