default_stages: [ commit, merge-commit, push, prepare-commit-msg, commit-msg,
                  post-checkout, post-commit, post-merge, post-rewrite ]
exclude: |
  (?x)(
  LICENSE|
  \.(html|csv|svg)$|
  EAB_tools/tools.py  # This is old code
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed.
      - id: check-ast  # Simply check whether files parse as valid python.
      - id: check-case-conflict  # Check for files with names that would conflict on a
                                 # case-insensitive filesystem like macOS HFS+ or
                                 # Windows FAT.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml  # checks toml files for parseable syntax.
      - id: check-yaml  # checks yaml files for parseable syntax.
      - id: destroyed-symlinks  # Detects symlinks which are changed to regular files
                                # with a content of a path which that symlink was
                                # pointing to. This usually happens on Windows when a
                                # user clones a repository that has symlinks, but they
                                # do not have the permission to create symlinks.
      - id: detect-private-key  # Checks for the existence of private keys.
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
      - id: mixed-line-ending  # Replaces or checks mixed line ending.
      - id: trailing-whitespace  # Trims trailing whitespace.

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.1.17
          - flake8-comprehensions==3.14.0
        args:
          - '--extend-ignore=E203'

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
        types:
          - python

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
          - tomli
        # Don't let `pre-commit` pass filenames
        # Instead, use `pydocstyle`'s default settings from pyproject.toml
        pass_filenames: false

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys=cell.metadata.pycharm']
        stages:
          - manual
      - id: nbstripout
        name: nbstripout pycharm metadata
        alias: nbstripout-pycharm
        args:
          - '--extra-keys=cell.metadata.pycharm'
          - --keep-output
          - --keep-count

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-check-ast
      - id: nbqa-flake8
        additional_dependencies:
          - flake8==7.0.0
          - flake8-bugbear==24.1.17
          - flake8-comprehensions==3.14.0
        args:
          - '--extend-ignore=E203,E402'
      - id: nbqa-isort
        additional_dependencies:
          - isort==5.13.2
      - id: nbqa-mypy
        additional_dependencies:
          - mypy==1.7.0
          - matplotlib  # for its type hints
        exclude: \.py$
      - id: nbqa-pyupgrade
        additional_dependencies:
          - pyupgrade==v3.15.0
        args:
          - --py39-plus  # Synchronize with args in regular hook
  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.27.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
