comment: false

coverage:
  status:
    project:
      default:
        # If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified.
        informational: true
    patch:
      default:
        informational: true

github_checks: false
