# This workflow will install Python dependencies, run pre-commit tests and lint
# with a variety of Python versions

name: Pre-Commit Tests - All OSes - Python 3.9, 3.10

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        foreach ($f in Get-ChildItem "*requirements*.txt")
        {
          python -m pip install -r $f
        }
        python -m pip install -e .
      shell: pwsh
    - name: Install flake8 and testing requirements
      run: |
        python -m pip install pytest flaky pytest-random-order flake8 pre-commit
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run pre-commit checks
      run: |
        python -m pre_commit run -a
