# This workflow will publish PyPI package on tags

name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Pytest Tests - All OSes - Python 3.9, 3.10"]
    types: [completed]
jobs:
  PyPI:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install -U pip setuptools wheel build
        python -m build
    - name: Lint with flake8
      run: |
        python -m pip install -U flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: troubleshoot
      run: |
        echo github.ref
        echo ${{ github.ref }}
        echo startsWith(github.ref, 'refs/tags')
        echo startsWith(${{ github.ref }}, 'refs/tags')
    - name: Publish Package
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
