# This workflow will publish PyPI package on tags

name: Publish to PyPI

on:
  workflow_run:
    workflows: ["pytest-tests"]

jobs:
  PyPI:
    runs-on: ubuntu-latest
    needs: pytest-tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install -U pip setuptools wheel build
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Publish Package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
