# This workflow will publish PyPI package on tags

name: Publish to PyPI

on:
  push:
    tags:
      # on all tags
      - '*'

jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build
      run: |
        python -m pip install -U pip setuptools wheel build
        python -m build
    - name: Lint with flake8
      run: |
        python -m pip install -U flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.1.2
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'PyPI'
        allowed-conclusions: success
        wait-interval: 120

    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
