# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest Tests - All OSes - Python 3.9, 3.10, 3.11

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  pytest-tests:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --editable .
        foreach ($f in Get-ChildItem "*requirements*.txt")
        {
          python -m pip install --requirement $f
        }
      shell: pwsh
    - name: Test with pytest
      run: >
        pytest
        --doctest-modules
        --random-order-seed=0
        --verbose
        -m 'slow or not slow'
        --durations=100
        --cov
        --cov-report=xml
        --cov-append

    - name: Report Coverage
      run: coverage report -m

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        flags: unittests,slow
        fail_ci_if_error: true
